with open(r'c:\Users\phams\Documents\Test\assessly\modules\README.md', 'r', encoding='utf-8') as f:
    content = f.read()

# Apply in this exact order (longest first to avoid partial matches)
replacements = [
    # Long compound words first
    ("Schluesselverwaltung", "Schlüsselverwaltung"),
    ("Schluesselpaar", "Schlüsselpaar"),
    ("Groessenlimit", "Größenlimit"),
    ("Moeglichkeiten", "Möglichkeiten"),
    ("Moeglichkeit", "Möglichkeit"),
    ("Verlaengerungsdatum", "Verlängerungsdatum"),
    ("verlaengerungsdatum", "verlängerungsdatum"),
    ("Verlaengerungen", "Verlängerungen"),
    ("verlaengerungen", "verlängerungen"),
    ("Verlaengerung", "Verlängerung"),
    ("verlaengerung", "verlängerung"),
    ("Rueckmeldung", "Rückmeldung"),
    ("rueckmeldung", "rückmeldung"),
    ("Ruecksetzung", "Rücksetzung"),
    ("ruecksetzung", "rücksetzung"),
    ("Uebermittlung", "Übermittlung"),
    ("uebermittlung", "übermittlung"),
    ("Uebertragung", "Übertragung"),
    ("uebertragung", "übertragung"),
    ("Uebersicht", "Übersicht"),
    ("uebersicht", "übersicht"),
    ("Uebergabe", "Übergabe"),
    ("uebergabe", "übergabe"),
    ("Pruefkommando", "Prüfkommando"),
    ("pruefkommando", "prüfkommando"),
    ("Pruefungen", "Prüfungen"),
    ("pruefungen", "prüfungen"),
    ("Pruefung", "Prüfung"),
    ("pruefung", "prüfung"),
    ("Pruefbar", "Prüfbar"),
    ("pruefbar", "prüfbar"),
    ("Schluessel", "Schlüssel"),
    ("schluessel", "schlüssel"),
    ("Verfuegbar", "Verfügbar"),
    ("verfuegbar", "verfügbar"),
    ("zuruecksetzen", "zurücksetzen"),
    ("Zuruecksetzen", "Zurücksetzen"),
    ("zurueck", "zurück"),
    ("Zurueck", "Zurück"),
    ("durchgefuehrt", "durchgeführt"),
    ("ausgefuehrt", "ausgeführt"),
    ("aufgefuehrt", "aufgeführt"),
    ("Ausfuehren", "Ausführen"),
    ("ausfuehren", "ausführen"),
    ("Ausfuehrung", "Ausführung"),
    ("ausfuehrung", "ausführung"),
    ("fuehren", "führen"),
    ("Fuehren", "Führen"),
    ("fuehrt", "führt"),
    ("Fuehrt", "Führt"),
    ("Kuerzer", "Kürzer"),
    ("kuerzer", "kürzer"),
    ("Haertere", "Härtere"),
    ("haertere", "härtere"),
    ("Haerter", "Härter"),
    ("haerter", "härter"),
    ("fuer", "für"),
    ("Ueber", "Über"),
    ("ueber", "über"),
    # oe → ö
    ("Benoetigen", "Benötigen"),
    ("benoetigen", "benötigen"),
    ("Benoetigt", "Benötigt"),
    ("benoetigt", "benötigt"),
    ("Groesse", "Größe"),
    ("groesse", "größe"),
    ("Loesungen", "Lösungen"),
    ("loesungen", "lösungen"),
    ("Loesung", "Lösung"),
    ("loesung", "lösung"),
    ("Oeffentlich", "Öffentlich"),
    ("oeffentlich", "öffentlich"),
    ("geoeffnet", "geöffnet"),
    ("Oeffnen", "Öffnen"),
    ("oeffnen", "öffnen"),
    ("Moeglich", "Möglich"),
    ("moeglich", "möglich"),
    ("Stoert", "Stört"),
    ("stoert", "stört"),
    # ae → ä
    ("Haeufige", "Häufige"),
    ("haeufige", "häufige"),
    ("Haeufig", "Häufig"),
    ("haeufig", "häufig"),
    ("Aenderungen", "Änderungen"),
    ("aenderungen", "änderungen"),
    ("Aenderung", "Änderung"),
    ("aenderung", "änderung"),
    ("Eintraegen", "Einträgen"),
    ("eintraegen", "einträgen"),
    ("Eintraege", "Einträge"),
    ("eintraege", "einträge"),
    ("Erklaert", "Erklärt"),
    ("erklaert", "erklärt"),
    ("Erlaeuterung", "Erläuterung"),
    ("erlaeuterung", "erläuterung"),
]

for old, new in replacements:
    content = content.replace(old, new)

with open(r'c:\Users\phams\Documents\Test\assessly\modules\README.md', 'w', encoding='utf-8') as f:
    f.write(content)

print("Done. Replacements applied.")
