// AUTO-GENERATED — do not edit manually. Run: node scripts/compute-themes-hash.mjs
// Regenerated by postinstall and prebuild scripts.
export const NEXT_THEMES_FOUC_HASH = 'sha256-QdZUWNKONs0aNHL51gbSsRMVJDHJlKnT7vl9c0aqdcA=';
