// AUTO-GENERATED — do not edit manually. Run: node scripts/compute-themes-hash.mjs
// Regenerated by postinstall and prebuild scripts.
export const NEXT_THEMES_FOUC_HASH = 'sha256-MYxhzeIX8kawDN1kIeAPB/U1lJFNKLImo8XfZ34hqdQ=';
