ALTER TABLE "User"
ADD COLUMN "mfaRecoveryCodes" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "mfaEnforced" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Company"
ADD COLUMN "mfaRequired" BOOLEAN NOT NULL DEFAULT false;
